const $=s=>document.querySelector(s),days=$('#days');
let memo={tasksByDate:{},rollLastDate:null}, checklist=[], visible=30, activeDate=null, logoData='';
const pad=n=>String(n).padStart(2,'0');
function keyFromDate(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function workDate(d=new Date()){const x=new Date(d);if(x.getHours()<3)x.setDate(x.getDate()-1);return keyFromDate(x)}
function shiftDate(k,n){const d=new Date(k+'T12:00:00');d.setDate(d.getDate()+n);return keyFromDate(d)}
function label(k){const d=new Date(k+'T12:00:00'),w='일월화수목금토'[d.getDay()];return `${k} ${w}요일`}
function tasks(k){return memo.tasksByDate[k]||(memo.tasksByDate[k]=[])}
async function saveAll(){await wontech.set('memoData',memo);await wontech.set('checklist',checklist)}
function rollover(){const today=workDate();let start=memo.rollLastDate||today;if(start>today)start=today;let cursor=start,guard=0;while(cursor<today&&guard<5000){const next=shiftDate(cursor,1),target=tasks(next),seen=new Set(target.map(x=>x.origin||x.id));tasks(cursor).filter(x=>x.status==='pending'&&x.text.trim()).forEach(x=>{const origin=x.origin||x.id;if(!seen.has(origin))target.push({id:crypto.randomUUID(),origin,text:x.text,status:'pending'})});cursor=next;guard++}memo.rollLastDate=today;}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function render(){days.innerHTML='';const t=workDate();for(let i=visible-1;i>=0;i--)days.append(makeDay(shiftDate(t,-i)));activeDate=activeDate||t;applyLogo();const chip=$('#currentWorkDate');if(chip)chip.textContent=label(t);}
function makeDay(k){const s=document.createElement('section');s.className='sheet';s.dataset.date=k;s.innerHTML=`<div class="brand"><img class="brand-logo" alt="WONTECH"><div class="date">DATE ${label(k)}</div></div><div class="head"><div>NO</div><div>업 무 내 용</div><div>진행상황</div><div></div></div><div class="list"></div><div class="footer-actions"><button>＋ 업무 추가</button></div><div class="summary"></div>`;const list=s.querySelector('.list'),arr=tasks(k);if(!arr.length)list.innerHTML='<div class="empty">등록된 업무가 없습니다.</div>';arr.forEach((x,i)=>list.append(row(k,x,i)));s.querySelector('.footer-actions button').onclick=()=>addTask(k);s.onclick=()=>{activeDate=k;document.querySelectorAll('.sheet').forEach(x=>x.classList.toggle('active-sheet',x.dataset.date===k))};const sm=s.querySelector('.summary');sm.innerHTML=`<span>전체 ${arr.length}</span><span class="done-c">완료 ${arr.filter(x=>x.status==='done').length}</span><span class="pending-c">미처리 ${arr.filter(x=>x.status==='pending').length}</span><span class="check-c">체크 ${arr.filter(x=>x.status==='check').length}</span>`;return s}
function row(k,x,i){const r=document.createElement('div');r.className='task '+(x.status||'');r.innerHTML=`<div class="num">${i+1}</div><input class="text" value="${esc(x.text)}" placeholder="업무 내용을 입력하세요"><select class="status"><option value="">선택</option><option value="pending">미처리</option><option value="done">완료</option><option value="check">체크</option></select><button class="remove">×</button>`;const input=r.querySelector('.text'),sel=r.querySelector('.status');sel.value=x.status||'';input.oninput=async e=>{x.text=e.target.value;const c=checklist.find(v=>v.sourceTaskId===x.id);if(c)c.text=x.text;await saveAll()};sel.onchange=async e=>{x.status=e.target.value;if(x.status==='check'){let c=checklist.find(v=>v.sourceTaskId===x.id);if(!c)checklist.push({id:crypto.randomUUID(),sourceTaskId:x.id,date:k,text:x.text,status:'pending'});else{c.date=k;c.text=x.text}}await saveAll();render();go(k)};r.querySelector('.remove').onclick=async e=>{e.stopPropagation();memo.tasksByDate[k]=tasks(k).filter(v=>v.id!==x.id);checklist=checklist.filter(v=>v.sourceTaskId!==x.id);await saveAll();render();go(k)};return r}
async function addTask(k=activeDate||workDate()){tasks(k).push({id:crypto.randomUUID(),text:'',status:''});await saveAll();render();go(k);setTimeout(()=>document.querySelector(`[data-date="${k}"] .task:last-child .text`)?.focus(),120)}
function go(k){activeDate=k;setTimeout(()=>document.querySelector(`[data-date="${k}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}),30)}
function applyLogo(){document.querySelectorAll('.brand-logo').forEach(x=>x.src=logoData);$('#toolbarLogo').src=logoData}
function targetSheet(){return document.querySelector(`[data-date="${activeDate||workDate()}"]`)||document.querySelector(`[data-date="${workDate()}"]`)}
async function withOutput(fn){const sheet=targetSheet();if(!sheet)return;document.body.classList.add('output-mode');sheet.classList.add('output-target');try{await new Promise(r=>setTimeout(r,100));return await fn(sheet)}finally{sheet.classList.remove('output-target');document.body.classList.remove('output-mode')}}
function fileBase(){return 'WONTECH_업무메모_'+(activeDate||workDate())}
function showNote(t){const n=$('#note');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1800)}
async function init(){memo=await wontech.get('memoData')||memo;memo.tasksByDate=memo.tasksByDate||{};checklist=await wontech.get('checklist')||[];logoData=await wontech.getLogo();rollover();await saveAll();render();go(workDate());}
$('#today').onclick=()=>go(workDate());$('#add').onclick=()=>addTask(workDate());$('#older').onclick=()=>{const old=visible;visible+=30;render();go(shiftDate(workDate(),-old))};
$('#checklist').onclick=()=>wontech.open('checklist');$('#quoteManager').onclick=()=>wontech.open('quote-manager');$('#orderManager').onclick=()=>wontech.open('order-manager');$('#attachments').onclick=()=>wontech.open('quote-tracking');$('#translator').onclick=()=>wontech.open('translator');
$('#changeLogo').onclick=async()=>{const d=await wontech.pickLogo();if(d){logoData=d;applyLogo();showNote('마크를 교체했습니다. 견적/발주 창에도 적용됩니다.')}};$('#top').onchange=e=>wontech.top(e.target.checked);
$('#print').onclick=()=>withOutput(async()=>{const r=await wontech.print();if(!r?.success&&r?.reason)alert('인쇄 오류: '+r.reason)});
$('#pdf').onclick=()=>withOutput(()=>wontech.pdf(fileBase()));
$('#jpg').onclick=()=>withOutput(async sheet=>{const c=await html2canvas(sheet,{scale:2,backgroundColor:'#fff',logging:false});await wontech.saveImage(c.toDataURL('image/jpeg',.95),fileBase())});
init();
